var availableTags = [
      "Aiquile",
      "Anzaldo (C. Villa de Anzaldo)",
      "Arani",
      "Arbieto",
      "Arque (C. Villa de Arque)",
      "Ayopaya (C. Villa de Independencia)",
      "Bolivar",
      "Capinota/ Sicaya",
      "Chimore",
      "Cliza",
      "Cochabamba 1",
      "Cochabamba 2",
      "Colcapirhua",
      "Colomi",
      "Mizque",
      "Morochata",
      "Omereque",
      "Pasorapa",
      "Pocona",
      "Pojo",
      "Puerto Villarroel",
      "Punata (C. Villa Punata)",
      "Quillacollo",
      "Sacaba",
      "Sacabamba",
      "San Benito (C. Villa Jose Quintin Mendoza)",
      "Santivañez (C. Villa Santivañez)",
      "Sipe Sipe",
      "Tacopaya",
      "Tapacari",
      "Tarata",
      "Tiquipaya",
      "Tiraque",
      "Toko",
      "Tolata",
      "Totora",
      "Vacas",
      "Vila Vila/ Alalay",
      "Villa Rivero/ Tacachi/ Cuchumuela (Villa G. Villarroel)",
      "Villa Tunari",
      "Vinto"
    ];
//jQuery('h1').css('color','green');
$( "input[name^='EstudiantesBusqueda[DISTRITO]" ).autocomplete({
    source: availableTags
});